# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
  Links: friends

# Customize
customize:
    logo:
        enabled: false
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: /images/icon.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: xehoth
        author_title: 明日は明日の风が吹く
        location: Chengdu, China
        follow: https://xehoth.cc
    highlight: tomorrow
    sidebar: right # sidebar position, options: left, right or leave it empty
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: /images/icon.gif # path to favicon
    social_links:
        github: https://github.com/xehoth
        google: https://plus.google.com/u/0/117315969636381308537
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tagcloud

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus:  # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: #your github ID
        repo: #the repo to store comments
        #Register an OAuth application, and you will get a client ID and a client secret.
        client_id: #your client ID
        client_secret: #your client secret
    livere: # enter livere uid here
    valine: # Valine Comment System https://github.com/xCss/Valine
        on:  # enter true to enable
        appId:  # enter the leancloud application appId here
        appKey: # enter the leancloud application appKey here
        notify: # enter true to enable <Mail notifier> https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
        verify: # enter true to enable <Validation code>
        placeholder: Just Do It # enter the comment box placeholder
    

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: false # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: PA0yJb7_EyP5Qc-ZwYQgHRLHOMmoLmAH7VpCjJr4_Ek # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key
    mathjax: true # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        雨宮千夏: https://uuz.moe/
        Menci: https://men.ci/
        q234rty: https://q234rty.top/
        Sengxian: https://www.sengxian.com/
        sxysxy: http://sxysxy.org/
        TonyZhao: https://tonyzhao.xyz/
        WerKeyTom_FTD: http://blog.csdn.net/werkeytom_ftd
        SHADYQWQ: http://reveries.farbox.com
        HenryLi: http://henryli.cn/
        hzwer: http://hzwer.com/
        Claris: http://www.cnblogs.com/clrs97/
        thhyj: https://thhyj.tech
        scarlyw: http://blog.csdn.net/scar_lyw
        dzyo: http://blog.csdn.net/qq_35649707
        gym: http://gyming.org
        Qizy: https://qizy.tech/
        wuvin: http://blog.leanote.com/wuvin/
        ihopenot: http://www.cnblogs.com/ihopenot
        Enigma: http://enigma.wang
        zrq: http://blog.csdn.net/beginendzrq
        YYY: http://yyy.is-programmer.com/
        lcr: http://blog.csdn.net/lcrtest
        jzhang1: http://blog.csdn.net/jzhang1

player:
    enable: true
    id: 391387277
    server: netease
    type: playlist
    mode: random
    auto: true

CDN:
    mathjax: //cdn.bootcss.com/mathjax/2.7.1/MathJax.js
    jquery: //cdn.bootcss.com/jquery/3.2.1/jquery.min.js
    font_awesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css
    Aplayer: //cdn.bootcss.com/aplayer/1.6.0/APlayer.min.js